### ISSUE TITLE
Julia vs. MATLAB

### ISSUE THREAD

**Issue by hsseung** [aamini/FastConv.jl#1]
Thanks for making this code available. I wonder whether the "FastConv" name is promising too much, though.

I did some benchmarks against MATLAB.  Julia seems comparable in 1D but MATLAB seems quite a bit faster in 2D. Presumably MATLAB is calling MKL?
```
julia> w = rand(5,5);
julia> s = rand(32,32);
julia> @time for iter=1:1000;convn(s,w);end
  0.424601 seconds (204.00 k allocations: 178.574 MB, 2.38% gc time)
julia> @time for iter=1:1000;convn(s,w);end
  0.491745 seconds (204.00 k allocations: 178.574 MB, 2.24% gc time)
julia> w = rand(3,3);
julia> @time for iter=1:1000;convn(s,w);end
  0.047446 seconds (8.00 k allocations: 9.415 MB)
julia> @time for iter=1:1000;convn(s,w);end
  0.048083 seconds (8.00 k allocations: 9.415 MB, 3.62% gc time)
```

```
>> s = rand(32,32);
>> w = rand(5,5);
>> tic;for iter=1:1000;conv2(s,w);end;toc
Elapsed time is 0.102509 seconds.
>> tic;for iter=1:1000;conv2(s,w);end;toc
Elapsed time is 0.027208 seconds.
>> w = rand(3,3);
>> tic;for iter=1:1000;conv2(s,w);end;toc
Elapsed time is 0.019014 seconds.
>> tic;for iter=1:1000;conv2(s,w);end;toc
Elapsed time is 0.018701 seconds.
```

**Comment by hsseung** [comment]
Oops just realized I need to use `fastconv` to force direct convolution.  Then the performance is more comparable for the 5x5 kernel.  I think `convn` chose FFT rather than direct for this kernel size.

**Comment by aamini** [comment]
Yes sorry for not specifying this more obviously: `fastconv` is the function which forces the direct meta-programmed version of convolutions, while `convn` may choose the FFT approach depending on your input size (like you said). 

The speedups for FastConv should be very comparable to MATLAB all around; however, the naming was really referring to the huge speedups obtained in only Julia (especially for small kernels where Julia forces the FFT overhead).

**Comment by RoyiAvital** [comment]
It would be amazing if you could utilize Intel IPP behind the scenes.

It will also be much faster.
