### ISSUE TITLE
Calculation

### ISSUE THREAD

**Issue by EasonSun** [aamini/FastConv.jl#2]
Thank you for this work!

I understand convolution in math and CV, but the result of running this code surprises me:
```
...
EX = convn(stack, sobel3_x/2);
ET = convn(stack, prewitt2_t/2);
println(size(stack))
println(size(sobel3_x/2))
println(size(EX))
println(size(prewitt2_t/2))
println(size(ET))
```
Output:
(4,4,2)
(3,3,2)
(6,6,3)   <-- How the output has this dimension?
(2,2,2)
(5,5,3)   <-- How the output has this dimension?

The convs I saw has output the same size as the input image. I am new to Julia so not clear about your codes... Could you explain how the codes get this result?

**Comment by aamini** [comment]
Depending on the specific mathematical/computational package there are various different ways of defining a convolution. Specifically, the ambiguities rise on what shape the final dimension should take. One definition states if the input sizes are (n1 x m1) and (n2 x m2) then the output of the convolution will have size (n1+n2-1 x m1+m2-1). This definition is referred to as "full" convolutions and is the default for most other packages (eg. Matlab, Python, etc). There are other variations of convolution computation (such as "same" and "valid") but these all derive from the "full" version.

As a result, at the moment, this package supports "full" convolution computation. According to the formulas above, the sizes you stated make perfect sense. In the future, the additional methods maybe added; however, like I said these can all be obtained directly from looking at the output of the current output. 

Hope this helps and makes sense!

**Comment by EasonSun** [comment]
Ah I got it. I was only aware of 2D convolution... Thank you!
